trigger:
  - none
  

pipelines:
- pipeline: khairajpamnani.spacegame-web-deploy
  source: khairajpamnani.spacegame-web-deploy
  trigger: 
    branches: [release]

variables:
    #buildConfiguration: 'Release'
    releaseBranchName: 'release'    

stages:
  - stage: 'Dev'
    displayName: 'Deploy to the dev environment'
    dependsOn: Build
    condition: |
      and
      (
        succeeded(),
        eq(variables['Build.SourceBranchName'], variables['releaseBranchName'])
      )
    jobs:
    - template: templates/deployjobs.yml
      parameters:
        envVAR: dev
        AppName: '$(webappnamedev)' 
    
  
  - stage: 'Test'
    displayName: 'Deploy to the test environment'
    dependsOn: Dev
    #condition: eq(variables['Build.Reason'], 'Schedule') #run whem build reason=Schedule            
    jobs:
    - template: templates/deployjobs.yml
      parameters:
        envVAR: test
        AppName: '$(webappnametest)'
    
      
  - stage: 'Staging'
    displayName: 'Deploy to the staging environment'
    dependsOn: Test
    jobs:
    - template: templates/deployjobs.yml
      parameters:
        envVAR: staging
        AppName: '$(webappnamestg)'